# Databricks notebook source
MODES 
WE HAVE FOUR MODES
1. APEND
2. OVERWRITE
3.ERROR
4.IGNORE

# COMMAND ----------

APEND - MEGRE OR UNION WITH EXISTING DATA
OVERWRITE- CLEAR OLD DATA AND REPLACE WITH NEW DATA
ERROR - IGNORE THE IF THERE IS ERROR
IGNORE - IGNORE THE AND WILL NOT WRITE THE DATA ALSO
